apiVersion: v1
kind: Pod
spec:
  containers:
    - name: bb2-node-js-react-sample-app-cbc-build
      image: "public.ecr.aws/f5g8o1y9/bb2-node-js-react-sample-app-cbc-build:latest"
      tty: true
      command: ["tail", "-f"]
      imagePullPolicy: Always
  nodeSelector:
      Agents: true
